name: Compare tests Ubuntu/Windows

on:
    pull_request:

jobs:
    test:
        strategy:
          matrix:
            os: [windows-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
          - uses: actions/checkout@v3

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: "3.10"

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run tests
            continue-on-error: true
            run: |
              pip install pytest pytest-html
              cd tests
              python -m pytest -v --html=report.html --self-contained-html
              mv report.html ../report.html

          - name: Archive test report
            uses: actions/upload-artifact@v3
            with:
              name: pytest-report
              path: report.html
